### PR TITLE
Only change the state if current and target states differ

### LINKED ISSUE #6: Scenes and automations do not work properly
## Current behavior

Currently, a scene or an automation which would result in the same state of the player (i.e. player is paused and scene says "pause"), will toggle the state. 

## Expected behavior

If the scene or an automation do not change the state of the speaker, it should not be toggled.

### PR DESCRIPTION
**Pull request by okonet**
This PR fixes #6 and adds prettier and lint-staged to the project.

### CODE REVIEW

**Comment by okonet** [comment]
Most relevant commit is https://github.com/jptaranto/homebridge-roon-outputs/pull/7/commits/7694b8dc0a6b590c6108ce205584aa1f0ad2deb2

**Comment by jptaranto** [comment]
Thanks @okonet, bit late to the game I know! No idea why I didn't see this earlier, but I am alive.

**Comment by okonet** [comment]
Could you cut a release? I'm still using my local version afaik :)

**Comment by jptaranto** [comment]
Will do yeah, just gotta test it locally.

**Pull request merged**
